# Generated by Django 5.2.1 on 2025-05-25 03:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=cloudinary.models.CloudinaryField(
                default="media/avatars/default.png",
                max_length=255,
                verbose_name="image",
            ),
        ),
    ]
