name: Pipeline
on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
          - name: Instalar Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.12'

          - name: Instalar uv
            run: |
              pip install --upgrade pip
              pip install uv

          - name: Instalar dependencias
            run: |
              uv install --dev

